### ISSUE TITLE
Move integration tests into a separate project

### ISSUE THREAD

**Issue by pledbrook** [piotrchowaniec/grails-hibernate-filter#3]
Now that Gradle is the underlying build tool, it's easy to set up multi project builds and have test apps depend on the plugin project. Doing this will benefit the plugin in several ways:
1. It won't have to mess around with plugin excludes
2. Integration tests will work (integration tests don't seem to work properly in plugin projects atm)
3. You can test multiple app configurations (if that becomes useful)

This approach was taken by the [Audi Logging plugin](https://github.com/robertoschwald/grails-audit-logging-plugin) if you want to see what the setup looks like.

**Comment by piotrchowaniec** [comment]
@pledbrook if you have time, please take a look at grails-hibernate-filter-3 branch for review. 

Thanks for your suggestions.

**Comment by pledbrook** [comment]
Yes, that's the basic idea. Great!
