### ISSUE TITLE
Dependency on datastore or hibernate plugin?

### ISSUE THREAD

**Issue by sergiomichels** [piotrchowaniec/grails-hibernate-filter#4]
I noticed that you have a dependency for an specific version of the grails datastore

`compile "org.grails:grails-datastore-gorm-hibernate4:4.0.7.RELEASE"`

Isn't better to depend on the hibernate plugin? Something like

`provided "org.grails.plugins:hibernate"`

**Comment by piotrchowaniec** [comment]
Check out 0.2.0 version of the plugin. It should work with current Grails version (3.1.9) and has changed dependency as you suggested.
